# Generated by Django 2.1.2 on 2019-02-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180119_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
