# Generated by Django 2.1.2 on 2019-02-12 11:29

import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190205_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=apps.accounts.storage.OverwriteStorage(), upload_to='avatars/'),
        ),
    ]
